models/post.py
from extensions import  db
from sqlalchemy import TIMESTAMP
from datetime import datetime


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    body = db.Column(db.String(255), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    created_at = db.Column(TIMESTAMP, default=datetime.utcnow, nullable=False, )
    comments = db.relationship('Comment', backref='post')

    def __init__(self, title, body, _userId):
        self.title = title
        self.body = body
        self.user_id = _userId

admin/routes.py
import sqlalchemy.sql
from flask import Blueprint, render_template, request, url_for
from flask_login import current_user
from flask_security import roles_accepted
from werkzeug.utils import secure_filename, redirect

from extensions import db
from models.comment import Comment
from models.post import Post
from models.user import User

admin = Blueprint('admin', __name__, static_folder='../static', template_folder='../templates')


@admin.route('/')
@roles_accepted('admin')
def dashboard():
    user = current_user.username
    return render_template('admin/dashboard.html', username=user, current_user=current_user)

@admin.route("/all-questions")
def questions():
    QSTNS = Post.query.all()
    questions = [];
    for qst in QSTNS:
        question = {}
        user = User.query.get(qst.user_id)
        question = {
            "user_id":qst.user_id,
            "id":qst.id,
            "title":qst.title,
            "body": qst.body,
            "created_at":qst.created_at,
            "user":user.username,
            "user_profile":user.username[0],
            "no_comments": qst.comments
        }
        questions.append(question)
    return  render_template("admin/questions.html", qsts=questions)



@admin.route("/tick", methods=[ 'POST'])
def tick_answer():

    value = request.form.get('check_answer')
    if str(value) == "checked":
        value = "None"
    elif str(value)=="None":
        value = "checked"

    comment = Comment.query.filter_by(id=request.form.get("post_id")).update({"ticked": value})
    db.session.commit()
    return redirect(request.referrer)

farmer/routes.py
import os
import re
from flask import  Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required
from flask_security import roles_accepted
from werkzeug.utils import secure_filename
from diagnose import DiseaseDiagnosis, MODEL
from extensions import db, bcrypt, SQLAlchemyError, OperationalError
from inference import remidies
from models.comment import Comment
from models.history import History
from models.location import Location
from models.post import Post
from models.user import User

farmer = Blueprint('farmer', __name__, static_folder='../static', template_folder='../templates')
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}

@farmer.route('/farmer', methods=['GET'])
@roles_accepted('farmer')
@login_required
def dashboard():
    return render_template('farmer/dashboard.html', current_user=current_user)

@farmer.route('/question/ask', methods=['GET'])
@login_required
def ask_question():
    return render_template("farmer/ask_question.html")

@farmer.route('/post-question', methods=['POST'])
@login_required
def post_question():
    if request.method == "POST":
        title = request.form.get('title')
        body = request.form.get('body')
        user_id = current_user.id
        post = Post(title, body, user_id)
        db.session.add(post)
        db.session.commit()
        flash("Question successfully posted ", "success")
        return redirect(url_for("farmer.my_posts"))
    return "error"

@farmer.route('/user/posts', methods=['GET'])
@login_required
def my_posts():
    posts = current_user.posts
    return render_template("farmer/questions.html", posts= posts)

@farmer.route('/comment', methods=['GET','POST'])
@login_required
def comment():
    if request.method=="POST":
        user_id = current_user.id
        _comment = request.form.get("comment")
        post_id = request.form.get("id")
        comment = Comment(_comment=_comment, _userId = user_id, _postId=post_id)
        db.session.add(comment)
        db.session.commit()
        flash("Answer successfully submitted", "success")
        return redirect(url_for('main.questions'))
    return render_template("main/questions.html")


@farmer.route('/profile', methods=['GET'])
@login_required
def edit_profile():
    user_info = current_user
    return render_template('farmer/profile.html', user=user_info)



@farmer.route('/save-profile', methods=['POST', 'GET'])
@login_required
def save_profile():
    username = request.form.get('username')
    email = request.form.get('email')
    phone = request.form.get('phone')
    street = request.form.get('street')
    city = request.form.get('city')
    country = request.form.get('country')
    try:
        user = User.query.filter_by(id=current_user.id).update({"username": username, "email": email, "phone": phone})
        location = Location.query.filter_by(user_id=current_user.id).update({"street": street, "city": city, "country": country})
    except SQLAlchemyError as e:
        flash(f"{str(e.__dict__['orig'])}", "alert text-center")
        db.session.rollback()
        redirect(url_for("farmer.edit_profile"))
    except OperationalError as o:
        flash(f"{str(o.__dict__['orig'])}", "alert text-center")
        db.session.rollback()
        return redirect(url_for("farmer.edit_profile"))
    else:
        db.session.commit()
    flash("Successfully edit user profile.", "success text-center")
    return redirect(url_for("farmer.edit_profile"))


@farmer.route('/change-password', methods=['POST', 'GET'])
@login_required
def change_password():
    old_pwd = request.form.get('old_password')
    new_pwd = request.form.get('new_password')
    confirm_pwd = request.form.get('password_confirm')
    user = User.query.filter_by(id=current_user.id).first()
    if user and user.verify_password(old_pwd):
        if new_pwd.__ne__(confirm_pwd):
            flash("Password does not match Password confirmation. Please match the passwords.", "alert")
            return redirect(url_for("farmer.edit_profile"))
        user = User.query.filter_by(id=current_user.id).update({"password": bcrypt.generate_password_hash(new_pwd)})
        db.session.commit()
        flash("Successfully change password!", "success text-center")
        return redirect(url_for("farmer.edit_profile"))
    flash("Incorrectly credentials. Please try again!", "alert text-center")
    return  redirect(url_for("farmer.edit_profile"))


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def get_disease_name(file):
    d = DiseaseDiagnosis()
    image = d.process_image(file)
    pred = d.predict(MODEL, image)
    disease = d.prediction_cls(pred)
    #disease = mappings[pred_v]
    return  disease, remidies[disease]

@farmer.route("/diagnosis", methods=['POST', 'GET'])
@login_required
@roles_accepted("farmer")
def diagnose():
    return render_template("farmer/diagnosis.html", disease="",image_url=None,remidy={"remidy":""})

def format_name(s):
   return re.sub('_+', ' ', s)

@farmer.route("/detect", methods=['POST', 'GET'])
@login_required
@roles_accepted("farmer")
def detect():
    diseas=""
    remidy=""
    if request.method == "POST":
        # check if the post request has the file part
        file = request.files['file']
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
        if file.filename == '':
            flash("No selected file",  "alert text-center")
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join('static/uploads', filename))
            diseas, remidy = get_disease_name(f"static/uploads/{filename}")
            keep_history(disease_name=diseas, user_id=current_user.id,image_url=filename)

            return render_template("farmer/diagnosis.html", disease=format_name(diseas), remidy=remidy, image_url=filename)
    return render_template("farmer/diagnosis.html", disease=diseas, remidy=remidy)


def keep_history(disease_name, user_id, image_url):
    history = History(disease=disease_name, user_id=user_id, image=image_url)
    db.session.add(history)
    db.session.commit()

@farmer.route("history/item/<id>", methods=['GET', 'POST'])
def delete_history(id):
    history = History.query.filter_by(id=id).first()
    db.session.delete(history)
    db.session.commit()
    flash("History item delete ", "success")
    return redirect(url_for("farmer.diagnosis_history"))


@farmer.route("diagnosis-history")
def diagnosis_history():
    history = current_user.history;
    return render_template("farmer/diagnosis_history.html", diagnosis_history = history, remidies=remidies,f=format_name)

main/routes.py
import flask_security
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required, login_user
from flask_security import logout_user, SQLAlchemyUserDatastore, roles_accepted
from werkzeug.security import check_password_hash

from models.location import Location
from models.post import Post
from models.role import Role
from models.user import User
from extensions import db, login_manager, bcrypt, SQLAlchemyError, OperationalError

main = Blueprint('main', __name__, static_folder='../static', template_folder='../templates')


def get_user(user_id):
    user = User.query.filter_by(id=user_id).first()
    return user


@login_manager.user_loader
def load_user(user_id):
    return get_user(user_id)

#LOGIN PAGE
@main.route('/login', methods=['GET'])
def login():
    return render_template('auth/login.html')

#LOGGIN IN
@main.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    # remember_me = True if request.form.get('remember') else False
    user = User.query.filter_by(email=email).first()
    if user and user.verify_password(password):
        login_user(user)

        flash(f"Hi {user.username}!", "success")

        if user.roles[0].name.__eq__("farmer"):
            return redirect(url_for('main.questions'))
        if user.roles[0].name.__eq__("admin"):
            return redirect(url_for('admin.questions'))
        else:
            flash("Error! Recreate your account, please", "alert")
            return "NO DEFINED ROLE"
    flash("Invalid Password/ Email. Please Try Again!", "alert")
    return render_template("auth/login.html")
@login_required
@main.route('/register', methods=['GET'])
def register():
    return render_template("auth/register.html")


user_datastore = SQLAlchemyUserDatastore(db, User, Role)
@main.route('/register', methods=[ 'POST'])
def add_farmer():
    if request.method == "POST":
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')
        password_confirm = request.form.get('password_confirm')
        if password.__ne__(password_confirm):
            flash("Password does not match Password confirmation. Please match the passwords.", "alert")
            return render_template("auth/register.html")
        # LOCATION
        street = request.form.get('street')
        city = request.form.get('city')
        country = request.form.get('country')

        farmer_role = Role(name='farmer')
        try:
            user = user_datastore.create_user(username=username, email=email,
                                              password=bcrypt.generate_password_hash(password), roles=[farmer_role])
            db.session.add(user)
            db.session.commit()
            location = Location(street=street, city=city, country=country, user_id=user.id)
            db.session.add(location)
            db.session.commit()
        except SQLAlchemyError as e:
            flash(f"{str(e.__dict__['orig'])}", "danger text-center")
            db.session.rollback()
            return render_template("auth/register.html")
        except OperationalError as o:
            flash(f"{str(o.__dict__['orig'])}", "danger text-center")
            db.session.rollback()
            return render_template("auth/register.html")
        else:
            db.session.commit()
        return redirect(url_for("main.login"))

@main.route("/questions")
def questions():
    QSTNS = Post.query.all()
    questions = [];
    for qst in QSTNS:
        question = {}
        user = User.query.get(qst.user_id)
        question = {
            "user_id":qst.user_id,
            "id":qst.id,
            "title":qst.title,
            "body": qst.body,
            "created_at":qst.created_at,
            "user":user.username,
            "user_profile":user.username[0],
            "no_comments": qst.comments
        }
        questions.append(question)
    return  render_template("main/questions.html", qsts=questions, current_user= current_user)

@main.route('/question/<id>', methods=['GET'])
def question(id):
    post = Post.query.get(id)
    user = User.query.get(post.user_id)
    _comments = post.comments
    comments = []
    for comment in _comments:
        _user = User.query.get(comment.user_id)
        comment ={"user":_user,"comment":comment}
        comments.append(comment)
    return render_template("main/post.html", post=post, user=user, comments=comments, current_user=current_user)

@main.route("/tags")
def tags():
    return render_template("main/tagged_qstns.html")


@main.route("/users")
def users():
    users = User.query.all()
    users = [user for user in users if user.roles[0]=="farmer"]
    return render_template("main/user_qstns.html", users=users)
@main.route("/user-posts/<id>")
def user_posts(id):
    posts = Post.query.filter_by(user_id = id).all()
    return render_template("farmer/questions.html", posts= posts)
@main.route("/")
def index():
    return render_template("index.html", current_user=current_user)

@main.route('/about')
def about():
    return render_template("about.html")

@main.route('/help')
def help():
    return render_template("help.html")

@main.route('/logout', methods=['POST', 'GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@main.route('/search/<text>',  methods=['GET'])
def search_by_id(text):
    search_results = Post.all()
    return render_template('main/search_qstns.html', object_frames=search_results, search_txt=text)

templates/main/index.html
{% extends "base.html" %}
{% block body %}
    <div class="farmer-dashboard">
        <nav class="navbar navbar-sm navbar-expand-md navbar-light shadow p-1 fixed-top"
             style="border-top: 3px solid #FF8000; background-color: #f2f2f2; position: sticky;">
            <div class="container-fluid">
                <a class="navbar-brand text-orange font-weight9 position-absolute" href="#" style="height: 30px; width: 30px; top: 0px;"><img src="{{url_for('static',filename = 'images/tomato(2).png')}}"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto font-weight5 text-13 text-secondary " style="margin-left: 70px">
                        {% if current_user.roles[0]!='admin' %}
                        <li class="nav-item active " style="margin-right: 18px">
                            <a class="nav-link text-black" href="/farmer/diagnosis">
                                <i class="fa fa-medkit"></i> Diagnose Diseases</a>
                        </li>
                    {% endif %}
                    {% if current_user.roles[0]=='admin' %}
                        <li class="nav-item  " style="margin-right: 18px">
                            <a class="nav-link text-black" href="/admin">
                                <i class="fa fa-tachometer"></i> Dashboard</a>
                        </li>
                    {% endif %}
                        <li class="nav-item " style="margin-right: 32px">
                          <a class="nav-link  pr-2 text-black text-13" href="/questions"><i class="fa fa-globe"></i>
                              Questions</a>
                        </li>
                        {% if current_user.roles[0]!='admin' %}
                         <li class="nav-item  " style="margin-right: 18px">
                            <a class="nav-link text-black text-13" href="/farmer/question/ask">
                                 <i class="fa fa-question-circle"></i>
                                Ask Question</a>
                        </li>
                        {% endif %}
                    </ul>
                <div style="width: 50%">
                    <form class="form-inline w-100">
                        <input class="form-control w-100 form-control-sm " placeholder="Search...">
                    </form>
                </div>
                <div class="navbar-nav ms-auto ">
                    {% if current_user.is_authenticated %}
                        <div style="margin-right: 5px">
                        <button class="p-3 pt-1  pb-1 text-uppercase btn btn-sm text-light font-weight7 bg-green text-13">{{ current_user.username[0] }}</button>
                         <a class="btn btn-sm btn-light text-13 p-2 font-weight4 pt-1 pb-1 border-green text-green" href="{{ url_for('main.logout') }}" >Logout</a></div>
                       </div>
                    {% else %}
                    <div style="margin-right: 5px">
                        <a href="/login" class="btn btn-sm btn-light text-13 p-2 font-weight4 pt-1 pb-1 border-green text-green" >Log in</a></div>
                    <div><a href="/register" class="btn btn-sm bg-green text-13 p-2 pt-1 text-white font-weight4 pb-1">Sign up</a></div>
                    {% endif %}
                </div>
            </div>
    </nav>
        <div>
         <div class="row">
            <div class="col-md-2 shadow" style="border-right: 1.5px solid #dedfe1; background-color: #F2F2F2;">
                <div class="w-100 fixed-top" style="position: sticky; top: 3em;">
                <div class="container p-2 pb-3 pt-2 border-bottom">
                    <a class="text-center heading text-brown font-weight9" href="/admin">
                        <span style="margin-left: 10px!important;"></span><span class="text-14" >HOME</span>
                    </a>
                </div>

                <div class="">
                    <span class="text-uppercase font-weight4 text-secondary text-12" style="margin-left:10px">Public</span>
                </div>

                <div class="">
                    <ul class=" list-unstyled text-13">
                    <li class=""><a class="navbar-link text-black" href="/questions">
                         <span class="fa-stack fa-lg font-weight6"><i class="fa fa-globe fa-stack-1x "></i></span>
                        <span class="text-13 font-weight5">Questions</span></a>
                        <ul class="text-13 m-1 ml-3">
                            <li class="p-1"><a class="navbar-link text-black" >Tags</a></li>
                            <li class="p-1"><a class="navbar-link text-black" href="/users">Users</a></li>
                        </ul>
                    </li>
                </ul>
                    <div class="">
                        <span class="text-uppercase font-weight4 text-secondary text-12" style="margin-left:10px">TEAM</span>
                    </div>
                    <div class="card  rounded-0 border-bottom " style="height: 350px; border-right:0">
                        <div class="card-body">
                            <p class="text-12 text-secondary">
                                <b>Farmers Community</b> – Collaborate and share knowledge with other farmers
                            </p>
                            <div class="" style="height: 150px;width: 100%">
                                <img src="{{url_for('static',filename = 'images/social-media-g47bd56e84_1920.png')}}">
                            </div>
                            <div class="p-1">
                                <button class="btn btn-sm bg-green text-12 text-white font-weight6 w-100">---------------</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
            <div class="col-md-10 p-1">
                <div class=" container-fluid p-1  bg-white">
                    <div class="pt-1">
                        {% with messages = get_flashed_messages(with_categories=true) %}
                            {% if messages %}
                                {% for category,msg in messages %}
                                <div class="card bg-{{ category }}">
                                    <div class="card-body p-1 text-white">
                                        <p class="text-13 font-weight6 m-1">{{ msg }}</p>
                                    </div>
                                </div>
                                {% endfor %}
                            {% endif %}
                        {% endwith %}
                        {% block dashboard_content %} {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>

        <div class="footer-farmer p-5 pb-3 bg-dark text-white" style="height: 200px">
             <div class="row ">
                 <div class="col-md-2">
                    <div style="height:100px!important; width: 100px!important;">
                           <img src="{{url_for('static',filename = 'images/tomato(2).png')}}">
                    </div>
                 </div>
                 <div class="col-md-3">
                     <div >
                       <h6 class="">Company</h6>
                         <ul class="list-unstyled text-12" style="color:#838C95">
                            <li>About</li>
                            <li>Contact Us</li>
                            <li>Privacy Policy</li>
                            <li>Terms and Conditions</li>
                        </ul>
                    </div>
                 </div>
                 <div class="col-md-3">
                         <div >
                           <h6>Company</h6>
                             <ul class="list-unstyled text-12" style="color:#838C95">
                                <li>Questions</li>
                                <li>Teams</li>
                                <li>Disease Diagnosis
                                 <li>Help</li>
                            </ul>
                        </div>
                 </div>
                 <div class="col-md-4">
                    <nav class="navbar navbar-sm navbar-expand-md">
                        <ul class="navbar-nav list-unstyled text-12" style="color:#838C95">
                            <li class="m-2 mr-4">Blog</li>
                            <li class="m-2 mr-4">Facebook</li>
                            <li class="m-2 mr-4">Twitter</li>
                            <li class="m-2 mr-4">Instagram</li>
                            <li class="m-2 mr-4">Linked In</li>
                        </ul>
                    </nav>
                 </div>
             </div>
         </div>
    </div>

{% endblock %}

templates/main/post.html
{% extends "main/index.html" %}
{% block dashboard_content %}
<div>
    <div class="row">
        <div class="col-md-10">
            <div container>
                <div class="p-2 pt-3 border-bottom">
                    <h4 class="font-weight6">{{ post.title }}</h4>
                    <div class="d-flex justify-content-between">
                         <p class=" text-12"><span class="text-secondary">Asked on</span> {{ post.created_at }}</p>
                        <div class="">
                            <a href="/user" class="text-10  shadow badge text-white bg-green ">{{ user.username }}</a>
                            <!--<button class="p-3 pt-1  pb-1 text-uppercase btn btn-sm text-light font-weight7 bg-green text-13" > <span class="text-12">{{ user.username[0] }}</span> </button>
-->
                        </div>
                    </div>
                </div>
                <div class="p-2">
                    <div class="card border-0 rounded-0" style="min-height: 100px; background-color: #F6F6F6!important;">
                        <div class="card-body">
                            <p class="text-13">{{ post.body }}</p>
                        </div>
                    </div>

                </div>
                <div class="p-3 border-bottom">
                    <h4>Comments</h4>
                </div>
                {% for cmt in comments %}
                    <div class="row">
                        <div class="col-md-1">

                            {% if current_user.is_authenticated and current_user.roles[0]=='admin' %}
                                <form  action="{{ url_for('admin.tick_answer') }}" method=post style="margin-top: 50px" class="text-center">
                                    <input class="d-none" value="{{ cmt.comment.id }}" name="post_id">
                                    <input class="d-none" type="checkbox" name="check_answer" {{ cmt.comment.ticked }}>
                                    <button class="btn btn-default " type="submit" ><input class="" type="checkbox" name="check_answer" {{ cmt.comment.ticked }}><small class="text-10 text-success font-weight6 badge shadow">save</small></button>
                                </form>
                            {% endif %}
                        {% if  current_user.roles[0]!='admin' and cmt.comment.ticked=="checked" %}
                            <div style="margin-top: 50px" class="text-center"><i class="fa fa-check text-success"></i></div>
                        {% endif %}
                        </div>
                        <div class="p-2 border-bottom col-md-11">
                            <div class="card border-0 rounded-0" style="min-height: 100px; background-color: #F6F6F6!important;">
                                <div class="card-body">
                                    <p class="text-13">{{ cmt.comment.comment }}</p>
                                </div>
                            </div>
                            <div class="d-flex justify-content-end">
                                <div class="d-flex flex-row">
                                    <span class="text-12 p-1 pt-2">Answered on</span>
                                    <p class="text-12 text-secondary p-1 pt-2">{{ cmt.comment.created_at }}</p>
                                    <div>
                                        <a class="text-10  shadow badge text-white" style="margin-left: 15px; background-color: #B75301">{{ cmt.user.username }}</a>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>

                {% endfor %}
                {% if current_user.is_authenticated and current_user.roles[0].name!='admin' %}
                <div class="p-2" >
                    <div class="p-1">
                        <h4>Your Answer</h4>
                    </div>
                    <form action="{{ url_for('farmer.comment') }}" method=post>
                        <textarea style="min-height: 120px" class="form-control form-control-sm" name="comment"></textarea>
                        <input class="d-none" value="{{ post.id }}" name="id">
                        <div class="p-1 pt-2">
                            {% if current_user.is_authenticated %}
                                <button type="submit" class="btn bg-green btn-sm text-12 text-white">Post Your Answer</button>
                            {% else %}
                                <div class=" d-flex flex-row" >
                                    <a style="margin-right: 5px" href="/login" class="btn btn-sm btn-light text-12 p-2 font-weight4 pt-1 pb-1 border-green text-green" >Log in</a>
                                    <a href="/register" class="btn btn-sm bg-green text-12 p-2 pt-1 text-white font-weight4 pb-1">Sign up</a>
                                </div>

                            {% endif %}
                        </div>
                    </form>
                </div>
                {%  endif %}
            </div>
        </div>
        <div class="col-md-2">
            <div class="p-2 pt-4">
                <a href="/farmer/question/ask" class="btn btn-sm bg-brown"><span class="text-white text-13">Ask Question</span></a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/main/user_qstns.html
{% extends "main/index.html" %}
{% block dashboard_content %}
    <div class="">
        <div>
             <div class="container-fluid border-bottom">
                    <div class="d-flex justify-content-between p-1 pb-2">
                        <span class="text-16">
                                {{ users | length }} Users
                        </span>
                    </div>
                    </div>

            <div class="row">
                {% for user in users %}
                <div class="col-md-3 d-flex justify-content-start">
                  <div class="d-flex flex-row justify-content-center p-3">
                        <div class="" style="height: 60px;width: 60px">
                            {% if user.profile_image=='' %}
                        <img class="rounded" src="images/{{ user.profile_image }}">
                            {% else %}
                            <div class="text-center shadow" style="padding: 20px; border-radius: 20%; background-color: rgba(0,60,255,0.47)">
                                <span class="font-weight7 text-17">
                                    {{ user.username[0] }}
                                </span>
                            </div>
                            {% endif %}
                        </div>
                        <div class="d-flex flex-column p-2">
                            <a href="{{ url_for("main.user_posts", id=user.id) }}" class="text-blue text-12 font-weight5" style="text-decoration: underline!important;">{{ user.username }}</a>
                            <span class="text-10">{{ user.location[0].city }}, {{ user.location[0].country }}</span>
                        </div>
                  </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}