farmer/routes.py
import os
import re
from flask import  Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required
from flask_security import roles_accepted
from werkzeug.utils import secure_filename
from diagnose import DiseaseDiagnosis, MODEL
from extensions import db, bcrypt, SQLAlchemyError, OperationalError
from inference import remidies
from models.comment import Comment
from models.history import History
from models.location import Location
from models.post import Post
from models.user import User

farmer = Blueprint('farmer', __name__, static_folder='../static', template_folder='../templates')
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}

@farmer.route('/farmer', methods=['GET'])
@roles_accepted('farmer')
@login_required
def dashboard():
    return render_template('farmer/dashboard.html', current_user=current_user)

@farmer.route('/question/ask', methods=['GET'])
@login_required
def ask_question():
    return render_template("farmer/ask_question.html")

@farmer.route('/post-question', methods=['POST'])
@login_required
def post_question():
    if request.method == "POST":
        title = request.form.get('title')
        body = request.form.get('body')
        user_id = current_user.id
        post = Post(title, body, user_id)
        db.session.add(post)
        db.session.commit()
        flash("Question successfully posted ", "success")
        return redirect(url_for("farmer.my_posts"))
    return "error"

@farmer.route('/user/posts', methods=['GET'])
@login_required
def my_posts():
    posts = current_user.posts
    return render_template("farmer/questions.html", posts= posts)

@farmer.route('/comment', methods=['GET','POST'])
@login_required
def comment():
    if request.method=="POST":
        user_id = current_user.id
        _comment = request.form.get("comment")
        post_id = request.form.get("id")
        comment = Comment(_comment=_comment, _userId = user_id, _postId=post_id)
        db.session.add(comment)
        db.session.commit()
        flash("Answer successfully submitted", "success")
        return redirect(url_for('main.questions'))
    return render_template("main/questions.html")


@farmer.route('/profile', methods=['GET'])
@login_required
def edit_profile():
    user_info = current_user
    return render_template('farmer/profile.html', user=user_info)



@farmer.route('/save-profile', methods=['POST', 'GET'])
@login_required
def save_profile():
    username = request.form.get('username')
    email = request.form.get('email')
    phone = request.form.get('phone')
    street = request.form.get('street')
    city = request.form.get('city')
    country = request.form.get('country')
    try:
        user = User.query.filter_by(id=current_user.id).update({"username": username, "email": email, "phone": phone})
        location = Location.query.filter_by(user_id=current_user.id).update({"street": street, "city": city, "country": country})
    except SQLAlchemyError as e:
        flash(f"{str(e.__dict__['orig'])}", "alert text-center")
        db.session.rollback()
        redirect(url_for("farmer.edit_profile"))
    except OperationalError as o:
        flash(f"{str(o.__dict__['orig'])}", "alert text-center")
        db.session.rollback()
        return redirect(url_for("farmer.edit_profile"))
    else:
        db.session.commit()
    flash("Successfully edit user profile.", "success text-center")
    return redirect(url_for("farmer.edit_profile"))


@farmer.route('/change-password', methods=['POST', 'GET'])
@login_required
def change_password():
    old_pwd = request.form.get('old_password')
    new_pwd = request.form.get('new_password')
    confirm_pwd = request.form.get('password_confirm')
    user = User.query.filter_by(id=current_user.id).first()
    if user and user.verify_password(old_pwd):
        if new_pwd.__ne__(confirm_pwd):
            flash("Password does not match Password confirmation. Please match the passwords.", "alert")
            return redirect(url_for("farmer.edit_profile"))
        user = User.query.filter_by(id=current_user.id).update({"password": bcrypt.generate_password_hash(new_pwd)})
        db.session.commit()
        flash("Successfully change password!", "success text-center")
        return redirect(url_for("farmer.edit_profile"))
    flash("Incorrectly credentials. Please try again!", "alert text-center")
    return  redirect(url_for("farmer.edit_profile"))


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def get_disease_name(file):
    d = DiseaseDiagnosis()
    image = d.process_image(file)
    pred = d.predict(MODEL, image)
    disease = d.prediction_cls(pred)
    #disease = mappings[pred_v]
    return  disease, remidies[disease]

@farmer.route("/diagnosis", methods=['POST', 'GET'])
@login_required
@roles_accepted("farmer")
def diagnose():
    return render_template("farmer/diagnosis.html", disease="",image_url=None,remidy={"remidy":""})

def format_name(s):
   return re.sub('_+', ' ', s)

@farmer.route("/detect", methods=['POST', 'GET'])
@login_required
@roles_accepted("farmer")
def detect():
    diseas=""
    remidy=""
    if request.method == "POST":
        # check if the post request has the file part
        file = request.files['file']
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
        if file.filename == '':
            flash("No selected file",  "alert text-center")
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join('static/uploads', filename))
            diseas, remidy = get_disease_name(f"static/uploads/{filename}")
            keep_history(disease_name=diseas, user_id=current_user.id,image_url=filename)

            return render_template("farmer/diagnosis.html", disease=format_name(diseas), remidy=remidy, image_url=filename)
    return render_template("farmer/diagnosis.html", disease=diseas, remidy=remidy)


def keep_history(disease_name, user_id, image_url):
    history = History(disease=disease_name, user_id=user_id, image=image_url)
    db.session.add(history)
    db.session.commit()

@farmer.route("history/item/<id>", methods=['GET', 'POST'])
def delete_history(id):
    history = History.query.filter_by(id=id).first()
    db.session.delete(history)
    db.session.commit()
    flash("History item delete ", "success")
    return redirect(url_for("farmer.diagnosis_history"))


@farmer.route("diagnosis-history")
def diagnosis_history():
    history = current_user.history;
    return render_template("farmer/diagnosis_history.html", diagnosis_history = history, remidies=remidies,f=format_name)

main/routes.py
import flask_security
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required, login_user
from flask_security import logout_user, SQLAlchemyUserDatastore, roles_accepted
from werkzeug.security import check_password_hash

from models.location import Location
from models.post import Post
from models.role import Role
from models.user import User
from extensions import db, login_manager, bcrypt, SQLAlchemyError, OperationalError

main = Blueprint('main', __name__, static_folder='../static', template_folder='../templates')


def get_user(user_id):
    user = User.query.filter_by(id=user_id).first()
    return user


@login_manager.user_loader
def load_user(user_id):
    return get_user(user_id)

#LOGIN PAGE
@main.route('/login', methods=['GET'])
def login():
    return render_template('auth/login.html')

#LOGGIN IN
@main.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    # remember_me = True if request.form.get('remember') else False
    user = User.query.filter_by(email=email).first()
    if user and user.verify_password(password):
        login_user(user)

        flash(f"Hi {user.username}!", "success")

        if user.roles[0].name.__eq__("farmer"):
            return redirect(url_for('main.questions'))
        if user.roles[0].name.__eq__("admin"):
            return redirect(url_for('admin.questions'))
        else:
            flash("Error! Recreate your account, please", "alert")
            return "NO DEFINED ROLE"
    flash("Invalid Password/ Email. Please Try Again!", "alert")
    return render_template("auth/login.html")
@login_required
@main.route('/register', methods=['GET'])
def register():
    return render_template("auth/register.html")


user_datastore = SQLAlchemyUserDatastore(db, User, Role)
@main.route('/register', methods=[ 'POST'])
def add_farmer():
    if request.method == "POST":
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')
        password_confirm = request.form.get('password_confirm')
        if password.__ne__(password_confirm):
            flash("Password does not match Password confirmation. Please match the passwords.", "alert")
            return render_template("auth/register.html")
        # LOCATION
        street = request.form.get('street')
        city = request.form.get('city')
        country = request.form.get('country')

        farmer_role = Role(name='farmer')
        try:
            user = user_datastore.create_user(username=username, email=email,
                                              password=bcrypt.generate_password_hash(password), roles=[farmer_role])
            db.session.add(user)
            db.session.commit()
            location = Location(street=street, city=city, country=country, user_id=user.id)
            db.session.add(location)
            db.session.commit()
        except SQLAlchemyError as e:
            flash(f"{str(e.__dict__['orig'])}", "danger text-center")
            db.session.rollback()
            return render_template("auth/register.html")
        except OperationalError as o:
            flash(f"{str(o.__dict__['orig'])}", "danger text-center")
            db.session.rollback()
            return render_template("auth/register.html")
        else:
            db.session.commit()
        return redirect(url_for("main.login"))

@main.route("/questions")
def questions():
    QSTNS = Post.query.all()
    questions = [];
    for qst in QSTNS:
        question = {}
        user = User.query.get(qst.user_id)
        question = {
            "user_id":qst.user_id,
            "id":qst.id,
            "title":qst.title,
            "body": qst.body,
            "created_at":qst.created_at,
            "user":user.username,
            "user_profile":user.username[0],
            "no_comments": qst.comments
        }
        questions.append(question)
    return  render_template("main/questions.html", qsts=questions, current_user= current_user)

@main.route('/question/<id>', methods=['GET'])
def question(id):
    post = Post.query.get(id)
    user = User.query.get(post.user_id)
    _comments = post.comments
    comments = []
    for comment in _comments:
        _user = User.query.get(comment.user_id)
        comment ={"user":_user,"comment":comment}
        comments.append(comment)
    return render_template("main/post.html", post=post, user=user, comments=comments, current_user=current_user)

@main.route("/tags")
def tags():
    return render_template("main/tagged_qstns.html")


@main.route("/users")
def users():
    users = User.query.all()
    users = [user for user in users if user.roles[0]=="farmer"]
    return render_template("main/user_qstns.html", users=users)
@main.route("/user-posts/<id>")
def user_posts(id):
    posts = Post.query.filter_by(user_id = id).all()
    return render_template("farmer/questions.html", posts= posts)
@main.route("/")
def index():
    return render_template("index.html", current_user=current_user)

@main.route('/about')
def about():
    return render_template("about.html")

@main.route('/help')
def help():
    return render_template("help.html")

@main.route('/logout', methods=['POST', 'GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@main.route('/search/<text>',  methods=['GET'])
def search_by_id(text):
    search_results = Post.all()
    return render_template('main/search_qstns.html', object_frames=search_results, search_txt=text)

templates/farmer/ask_question.html
{% extends "farmer/dashboard.html" %}
{% block dashboard_content %}
<div class="" style="background-color: #f2f2f2">
        <div class="container-fluid p-3 pt-1">
     <div class="p-3" >
                 <div class="d-flex justify-content-between">
                <h5 class="font-weight6 ">Ask Question</h5>
            </div>
    </div>

    <div class="row">
        <div class="col-md-8">
            <div class="card rounded-0 p-3 m-1" >
        <div class="card-body">
            <form action="{{ url_for('farmer.post_question') }}" method=post>
                <div class="form-group  mb-4">
                    <h6 class="font-weight6 text-14 p-1">Title</h6>
                    <small class="text-12 p-1">Be specific and imagine you’re asking a question to another person</small>
                    <div class="form-group">
                        <input class="form-control " name="title"  style="border-color: #BABFC4!important;">
                    </div>
                </div>
                <div class="form-group">
                    <h6 class="font-weight6 text-14 p-1">Body</h6>
                    <small class="text-12 p-1">Include all the information someone would need to answer your question</small>
                    <textarea class="form-control form-control-sm" name="body" style="min-height: 170px; border-color: #BABFC4!important;">
                    </textarea>
                </div>
                <div class="m-2 mt-3">
                    <button class="btn btn-sm text-13 bg-green rounded-0  text-white ">Post your question</button>
                </div>
            </form>
        </div>
    </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                         Steps: Draft your question
                    </div>
                </div>
                <div class="card-body">
                    <p class="text-12">The community is here to help you with specific tomato disease problems, or tomato farming problems. </p>
                    <p class="text-12">Avoid asking opinion-based questions.</p>
                    <div class="accordion" id="accordionPanelsStayOpenExample">
  <div class="accordion-item">
    <h6 class="accordion-header rounded-0 p-2" id="panelsStayOpen-headingOne">
      <button class="accordion-button btn-sm text-13" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
        <strong class="text-green">1.</strong> Summarize the problem
      </button>
    </h6>
    <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
      <div class="accordion-body">
                  <ul class=" text-12">
                      <li class="m-2">Include details about your goal</li>
                      <li class="m-2">Describe expected and actual results</li>
                      <li class="m-2">Include any challenges</li>
                  </ul>

      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header rounded-0 p-2" id="panelsStayOpen-headingTwo">
      <button class="accordion-button btn-sm collapsed text-13" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
        <strong class="text-green text-13">2.</strong>Describe what you’ve tried
      </button>
    </h2>
    <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
      <div class="accordion-body">
          <p class="text-12">
             Show what you’ve tried and tell us what you found (on this site or elsewhere) and
          why it didn’t meet your needs. You can get better answers when you provide research.
         </p>
      </div>
    </div>
  </div>
</div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/farmer/dashboard.html
{% extends "base.html" %}
{% block body %}
    <div class="farmer-dashboard">
        <nav class="navbar navbar-sm navbar-expand-md navbar-light shadow p-1 fixed-top"
             style="border-top: 3px solid #FF8000; background-color: #f2f2f2; position: sticky;">
            <div class="container-fluid">
                <a class="navbar-brand text-orange font-weight9 position-absolute" href="#" style="height: 30px; width: 30px; top: 0px;"><img src="{{url_for('static',filename = 'images/tomato(2).png')}}" ></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto font-weight5 text-13 text-secondary " style="margin-left: 70px">
                        {% if current_user.roles[0]!='admin' %}
                        <li class="nav-item  " style="margin-right: 18px">
                            <a class="nav-link text-black" href="/farmer/diagnosis">
                                <i class="fa fa-medkit"></i> Diagnose Diseases</a>
                        </li>
                        {% endif %}
                     {% if current_user.roles[0]=='admin' %}
                        <li class="nav-item  " style="margin-right: 18px">
                            <a class="nav-link text-black" href="/admin">
                                <i class="fa fa-tachometer"></i> Dashboard</a>
                        </li>
                    {% endif %}
                        <li class="nav-item " style="margin-right: 35px">
                          <a class="nav-link  pr-2 text-black text-13" href="/questions"><i class="fa fa-globe"></i>
                              Questions</a>
                        </li>
                    {% if current_user.roles[0]!='admin' %}
                        <li class="nav-item  " style="margin-right: 20px">
                            <a class="nav-link text-black text-13" href="/farmer/question/ask">
                                 <i class="fa fa-question-circle"></i>
                                Ask Question</a>
                        </li>
                    {% endif %}

                    </ul>
                <div style="width: 50%">
                    <form class="form-inline w-100">
                        <input class="form-control w-100 form-control-sm " placeholder="Search...">
                    </form>
                </div>
                <div class="navbar-nav ms-auto ">
                    {% if current_user.is_authenticated %}
                        <div style="margin-right: 5px">
                        <button class="p-3 pt-1  pb-1 text-uppercase btn btn-sm text-light font-weight7 bg-green text-13">{{ current_user.username[0] }}</button>
                         <a class="btn btn-sm btn-light text-13 p-2 font-weight4 pt-1 pb-1 border-green text-green" href="{{ url_for('main.logout') }}" >Logout</a></div>
                       </div>
                    {% else %}
                    <div style="margin-right: 5px">
                        <a href="/login" class="btn btn-sm btn-light text-13 p-2 font-weight4 pt-1 pb-1 border-green text-green" >Log in</a></div>
                    <div><a href="/register" class="btn btn-sm bg-green text-13 p-2 pt-1 text-white font-weight4 pb-1">Sign up</a></div>
                    {% endif %}
                </div>
            </div>
    </nav>
        <div>
         <div class="row">
            <div class="col-md-2 shadow-lg" style="border-right: 1.5px solid #dedfe1; ">
                <div class="w-100 fixed-top" style="min-height: 550px;position: sticky; top: 3em;" >
                <div class="container p-2 pb-3 pt-2 border-bottom">
                    <a class="text-center heading text-orange font-weight9" href="/">
                        <span style="margin-left: 10px!important;"></span><span class="text-14" >HOME</span>
                    </a>
                </div>

                <!--<div class="">
                    <span class="text-uppercase font-weight4 text-secondary text-12" style="margin-left:10px">Public</span>
                </div>-->

                <div class="">
                    <ul class=" list-unstyled text-13">
                        <li class=""><a class="navbar-link text-green">
                             <span class="fa-stack fa-lg font-weight6"><i class="fa fa-medkit fa-stack-1x "></i></span>
                            <span class="text-13 font-weight5">DISEASE DIAGNOSIS</span></a>
                            <ul class="text-13 m-1 ml-3">
                                <li class="p-1"><a class="navbar-link text-black" href="/farmer/diagnosis">Diagnose Disease</a></li>
                                <li class="p-1"><a class="navbar-link text-black" href="/farmer/diagnosis-history">Diagnosis History</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class=" list-unstyled text-13">
                        <li class=""><a class="navbar-link text-green">
                             <span class="fa-stack fa-lg font-weight6"><i class="fa fa-paper-plane fa-stack-1x "></i></span>
                            <span class="text-13 font-weight5">POSTS</span></a>
                            <ul class="text-13 m-1 ml-3 ">
                                <li class="p-1"><a class="navbar-link text-black" href="/farmer/user/posts">My Posts</a></li>
                                <!--<li class="p-1"><a class="navbar-link text-black" href="/user/comments">My Comments</a></li>-->
                            </ul>
                        </li>
                    </ul>
                    <ul class=" list-unstyled text-13">
                        <li class=""><a class="navbar-link text-green" href="/questions">
                             <span class="fa-stack fa-lg font-weight6"><i class="fa fa-gear fa-stack-1x "></i></span>
                            <span class="text-13 font-weight5">SETTINGS</span></a>
                            <ul class="text-13 m-1 ml-3">
                                <li class="p-1"><a class="navbar-link text-black" href="/farmer/profile">Profile Settings</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            </div>
            <div class="col-md-10 p-1">
                <div class=" container-fluid p-1  bg-white">
                    <div class="pt-1">
                        {% with messages = get_flashed_messages(with_categories=true) %}
                            {% if messages %}
                                {% for category,msg in messages %}
                                <div class="card bg-{{ category }}">
                                    <div class="card-body p-1 text-white">
                                        <p class="text-13 font-weight6 m-1">{{ msg }}</p>
                                    </div>
                                </div>
                                {% endfor %}
                            {% endif %}
                        {% endwith %}
                        {% block dashboard_content %} {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>

        <div class="footer-farmer p-5 pb-3 bg-dark text-white" style="height: 200px">
             <div class="row ">
                 <div class="col-md-2">
                    <div style="height:100px!important; width: 100px!important;">
                           <img src="{{url_for('static',filename = 'images/tomato(2).png')}}">
                    </div>
                 </div>
                 <div class="col-md-3">
                     <div >
                       <h6 class="">Company</h6>
                         <ul class="list-unstyled text-12" style="color:#838C95">
                            <li>About</li>
                            <li>Contact Us</li>
                            <li>Privacy Policy</li>
                            <li>Terms and Conditions</li>
                        </ul>
                    </div>
                 </div>
                 <div class="col-md-3">
                         <div >
                           <h6>Company</h6>
                             <ul class="list-unstyled text-12" style="color:#838C95">
                                <li>Questions</li>
                                <li>Teams</li>
                                <li>Disease Diagnosis
                                 <li>Help</li>
                            </ul>
                        </div>
                 </div>
                 <div class="col-md-4">
                    <nav class="navbar navbar-sm navbar-expand-md">
                        <ul class="navbar-nav list-unstyled text-12" style="color:#838C95">
                            <li class="m-2 mr-4">Blog</li>
                            <li class="m-2 mr-4">Facebook</li>
                            <li class="m-2 mr-4">Twitter</li>
                            <li class="m-2 mr-4">Instagram</li>
                            <li class="m-2 mr-4">Linked In</li>
                        </ul>
                    </nav>
                 </div>
             </div>
         </div>
    </div>

{% endblock %}

templates/farmer/profile.html
{% extends "farmer/dashboard.html"%}
{% block dashboard_content %}
    <div >
        <div class="container p-3">
            <div class="card m-2 shadow">
                <div class="card-body text-13">
                    <form method=post action="{{ url_for("farmer.save_profile") }}" role="form">
                        <h5 class="p-2">Edit Profile</h5>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Name</label>
                                    <div class=""><input type="text" class="form-control form-control-sm" name="username" value="{{ user }}" required></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Email</label>
                                    <div class=""><input type="email" class="form-control form-control-sm" name="email" value="{{ user.email }}" required></div>
                                </div>
                            </div>
                        </div>

                        <!--<div class="row">
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Phone</label>
                                    <div class=""><input type="text" class="form-control form-control-sm" name="phone" value="{{ user.phone }}" required></div>
                                </div>
                            </div>
                        </div>-->

                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Address</label>
                                    <div class=""><input type="text" class="form-control form-control-sm" name="street" value="{{ user.location[0].street }}" required></div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group m-1">
                                    <label class="font-weight7">City</label>
                                    <div class=""><input type="text" class="form-control form-control-sm" name="city" value="{{ user.location[0].city }}" required></div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Country</label>
                                    <div class=""><input type="text" class="form-control form-control-sm" name="country" value="{{ user.location[0].country }}" required></div>
                                </div>
                            </div>
                        </div>
                        <div class="m-2">
                            <button type="submit" class="btn btn-sm bg-green text-white text-13">Save Changes</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card m-1 shadow">
                <div class="card-body text-13">
                    <form class="" role="form" method=post action="{{ url_for("farmer.change_password") }}">
                        <h5 class="">Change Password</h5>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Old Password</label>
                                    <div class=""><input type="password" class="form-control form-control-sm" name="old_password" required></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">New Password</label>
                                    <div class=""><input type="password" class="form-control form-control-sm" name="new_password" required></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Password Confirmation</label>
                                    <div class=""><input type="password" class="form-control form-control-sm" name="password_confirm" required></div>
                                </div>
                            </div>
                        </div>
                         <div class="m-2">
                            <button type="submit" class="btn btn-sm bg-green text-white text-13">Save Password</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}